# Generated by Django 2.0.5 on 2018-05-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='type',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
